# Generated by Django 2.2 on 2020-06-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_number', models.IntegerField(default=2)),
                ('minimum_number', models.IntegerField(default=1)),
                ('number_of_inputs', models.IntegerField(default=6)),
            ],
        ),
    ]
